# Project: PokemonProject
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o trainer.o pokemon.o gym.o battle.o
LINKOBJ  = main.o trainer.o pokemon.o gym.o battle.o
LIBS     = -L"C:/ProgramFiles/Dev-Cpp/MinGW64/lib" -L"C:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/ProgramFiles/Dev-Cpp/MinGW64/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/ProgramFiles/Dev-Cpp/MinGW64/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/ProgramFiles/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = PokemonProject.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

trainer.o: trainer.c
	$(CC) -c trainer.c -o trainer.o $(CFLAGS)

pokemon.o: pokemon.c
	$(CC) -c pokemon.c -o pokemon.o $(CFLAGS)

gym.o: gym.c
	$(CC) -c gym.c -o gym.o $(CFLAGS)

battle.o: battle.c
	$(CC) -c battle.c -o battle.o $(CFLAGS)
